source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Raccoon_Example', :exclusive => true do
  pod 'Raccoon', :path => '../'
end

target 'Raccoon_Tests', :exclusive => true do
  pod 'Raccoon', :path => '../'

  
end
